/**
 ******************************************************************************
 * @file    vd1943_steval-1943mc1.h
 * @author  AIS Application Team
 * @brief   Header file for IQT parameters of the ISP middleware.
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under SLA0044 terms that can be found here:
 * https://www.st.com/resource/en/license_agreement/SLA0044.txt
 *
 * THIS FILE WAS GENERATED BY THE STM32 ISP IQTune ON 2026-04-02 14:27:05
 *
 ******************************************************************************
 */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __VD1943_ISP_PARAM_CONF__H
#define __VD1943_ISP_PARAM_CONF__H

/* DCMIPP ISP configuration for Vd1943 sensor */
static const ISP_IQParamTypeDef ISP_IQParamCacheInit_VD1943 = {
    .sensorGainStatic = {
        .gain = 0,
    },
    .sensorExposureStatic = {
        .exposure = 0,
    },
    .AECAlgo = {
        .enable = 1,
        .exposureCompensation = EXPOSURE_TARGET_0_0_EV,
        .antiFlickerFreq = ANTIFLICKER_NONE,
    },
    .statRemoval = {
        .enable = 0,
        .nbHeadLines = 0,
        .nbValidLines = 0,
    },
    .badPixelStatic = {
        .enable = 0,
        .strength = 0,
    },
    .badPixelAlgo = {
        .enable = 0,
        .threshold = 0,
    },
    .blackLevelStatic = {
        .enable = 1,
        .BLCR = 2,
        .BLCG = 2,
        .BLCB = 2,
    },
    .demosaicing = {
        .enable = 1,
        .type = ISP_DEMOS_TYPE_GBRG,
        .peak = 2,
        .lineV = 4,
        .lineH = 4,
        .edge = 6,
    },
    .ispGainStatic = {
        .enable = 0,
        .ispGainR = 0,
        .ispGainG = 0,
        .ispGainB = 0,
    },
    .colorConvStatic = {
        .enable = 0,
        .coeff = { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, }
    },
    .AWBAlgo = {
        .enable = 1,
        .label = {
            "A",
            "TL84",
            "D65"
    },
        .referenceColorTemp = {
            2856,
            4000,
            6500
    },
        .ispGainR = {
            100000000,
            127000000,
            166000000
    },
        .ispGainG = {
            110000000,
            100000000,
            100000000
    },
        .ispGainB = {
            315000000,
            242000000,
            154000000
    },
        .coeff = {
            { { 102099999, 85820000, -87920000, }, { -54279999, 180880000, -26590000, }, { -27710000, -51449999, 179150000, }, },
            { { 115290000, 34670000, -49960000, }, { -45690000, 168020000, -22330000, }, { -9690000, -38330000, 148020000, }, },
            { { 116910000, 50940000, -67850000, }, { -41150000, 184040000, -42890000, }, { -12830000, -26329999, 139160000, }, }
    },
        .referenceRGB = {
            { 68, 50, 18},
            { 53, 56, 22},
            { 42, 56, 34}
    },
    },
    .contrast = {
        .enable = 0,
        .coeff.LUM_0 = 0,
        .coeff.LUM_32 = 0,
        .coeff.LUM_64 = 0,
        .coeff.LUM_96 = 0,
        .coeff.LUM_128 = 0,
        .coeff.LUM_160 = 0,
        .coeff.LUM_192 = 0,
        .coeff.LUM_224 = 0,
        .coeff.LUM_256 = 0,
    },
    .statAreaStatic = {
        .X0 = 512,
        .Y0 = 397,
        .XSize = 1536,
        .YSize = 1190,
    },
    .gamma = {
        .enable = 1,
    },
    .sensorDelay = {
        .delay = 4,
    },
    .luxRef = {
        .HL_LuxRef = 1000,
        .HL_Expo1 = 400,
        .HL_Lum1 = 26,
        .HL_Expo2 = 2000,
        .HL_Lum2 = 124,
        .LL_LuxRef = 100,
        .LL_Expo1 = 4260,
        .LL_Lum1 = 27,
        .LL_Expo2 = 9860,
        .LL_Lum2 = 65,
        .calibFactor = 0.984f,
    },
};

static const ISP_IQParamTypeDef* ISP_IQParamCacheInit[] = {
    &ISP_IQParamCacheInit_VD1943
};

#endif /* __VD1943_ISP_PARAM_CONF__H */
