/**
 ******************************************************************************
 * @file    isp_param_conf.h
 * @author  AIS Application Team
 * @brief   Header file for IQT parameters of the ISP middleware.
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under SLA0044 terms that can be found here:
 * https://www.st.com/resource/en/license_agreement/SLA0044.txt
 *
 * THIS FILE WAS GENERATED BY THE STM32 ISP IQTune ON 2026-04-02 14:28:21
 *
 ******************************************************************************
 */

#ifndef __ISP_PARAM_CONF__H
#define __ISP_PARAM_CONF__H


/* DCMIPP ISP configuration for VD65G4 sensor */
static const ISP_IQParamTypeDef ISP_IQParamCacheInit_VD65G4 = {
    .sensorGainStatic = {
        .gain = 0,
    },
    .sensorExposureStatic = {
        .exposure = 15744,
    },
    .AECAlgo = {
        .enable = 1,
        .exposureCompensation = EXPOSURE_TARGET_0_0_EV,
        .antiFlickerFreq = ANTIFLICKER_NONE,
    },
    .statRemoval = {
        .enable = 0,
        .nbHeadLines = 0,
        .nbValidLines = 0,
    },
    .badPixelStatic = {
        .enable = 0,
        .strength = 0,
    },
    .badPixelAlgo = {
        .enable = 0,
        .threshold = 0,
    },
    .blackLevelStatic = {
        .enable = 1,
        .BLCR = 2,
        .BLCG = 2,
        .BLCB = 2,
    },
    .demosaicing = {
        .enable = 1,
        .type = ISP_DEMOS_TYPE_RGGB,
        .peak = 2,
        .lineV = 4,
        .lineH = 4,
        .edge = 6,
    },
    .ispGainStatic = {
        .enable = 0,
        .ispGainR = 0,
        .ispGainG = 0,
        .ispGainB = 0,
    },
    .colorConvStatic = {
        .enable = 0,
        .coeff = { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, }
    },
    .AWBAlgo = {
        .enable = 1,
        .label = {
            "A",
            "TL84",
            "D65"
    },
        .referenceColorTemp = {
            2856,
            4000,
            6500
    },
        .ispGainR = {
            100000000,
            122000000,
            172000000
    },
        .ispGainG = {
            106000000,
            100000000,
            100000000
    },
        .ispGainB = {
            311000000,
            235000000,
            150000000
    },
        .coeff = {
            { { 138230000, 33940000, -72170000, }, { -49740000, 180230000, -30490000, }, { -15709999, -90710000, 206420000, }, },
            { { 152430000, -2270000, -50160000, }, { -41970000, 166530000, -24560000, }, { -5130000, -66360000, 171490000, }, },
            { { 140910000, 19940000, -60850000, }, { -34010000, 185640000, -51630000, }, { -10900000, -27230000, 138140000, }, }
    },
        .referenceRGB = {
            { 65, 52, 18},
            { 54, 57, 23},
            { 39, 56, 36}
    },
    },
    .contrast = {
        .enable = 0,
        .coeff.LUM_0 = 0,
        .coeff.LUM_32 = 0,
        .coeff.LUM_64 = 0,
        .coeff.LUM_96 = 0,
        .coeff.LUM_128 = 0,
        .coeff.LUM_160 = 0,
        .coeff.LUM_192 = 0,
        .coeff.LUM_224 = 0,
        .coeff.LUM_256 = 0,
    },
    .statAreaStatic = {
        .X0 = 160,
        .Y0 = 140,
        .XSize = 480,
        .YSize = 420,
    },
    .gamma = {
        .enable = 1,
    },
    .sensorDelay = {
        .delay = 5,
    },
    .luxRef = {
        .HL_LuxRef = 1000,
        .HL_Expo1 = 1200,
        .HL_Lum1 = 35,
        .HL_Expo2 = 3600,
        .HL_Lum2 = 106,
        .LL_LuxRef = 100,
        .LL_Expo1 = 9720,
        .LL_Lum1 = 28,
        .LL_Expo2 = 21720,
        .LL_Lum2 = 65,
        .calibFactor = 0.988f,
    },
};

static const ISP_IQParamTypeDef* ISP_IQParamCacheInit[] = {
    &ISP_IQParamCacheInit_VD65G4
};

#endif /* __ISP_PARAM_CONF__H*/
