/**
 ******************************************************************************
 * @file    isp_param_conf.h
 * @author  AIS Application Team
 * @brief   Header file for IQT parameters of the ISP middleware.
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under SLA0044 terms that can be found here:
 * https://www.st.com/resource/en/license_agreement/SLA0044.txt
 *
 * THIS FILE WAS GENERATED BY THE STM32 ISP IQTune ON 2026-07-27 17:14:50
 *
 ******************************************************************************
 */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __ISP_PARAM_CONF__H
#define __ISP_PARAM_CONF__H

/* DCMIPP ISP configuration for IMX477 sensor */
static const ISP_IQParamTypeDef ISP_IQParamCacheInit_IMX477 = {
    .sensorGainStatic = {
        .gain = 0,
    },
    .sensorExposureStatic = {
        .exposure = 0,
    },
    .AECAlgo = {
        .enable = 1,
        .exposureCompensation = EXPOSURE_TARGET_0_0_EV,
        .antiFlickerFreq = ANTIFLICKER_NONE,
    },
    .statRemoval = {
        .enable = 0,
        .nbHeadLines = 0,
        .nbValidLines = 0,
    },
    .badPixelStatic = {
        .enable = 0,
        .strength = 0,
    },
    .badPixelAlgo = {
        .enable = 0,
        .threshold = 0,
    },
    .blackLevelStatic = {
        .enable = 1,
        .BLCR = 16,
        .BLCG = 16,
        .BLCB = 16,
    },
    .demosaicing = {
        .enable = 1,
        .type = ISP_DEMOS_TYPE_BGGR,
        .peak = 2,
        .lineV = 4,
        .lineH = 4,
        .edge = 6,
    },
    .ispGainStatic = {
        .enable = 0,
        .ispGainR = 0,
        .ispGainG = 0,
        .ispGainB = 0,
    },
    .colorConvStatic = {
        .enable = 0,
        .coeff = { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, }
    },
    .AWBAlgo = {
        .enable = 1,
        .label = { "JudgeII-A", "JudgeII-TL84", "JudgeII-DAY", "", "", },
        .referenceColorTemp = { 2810, 4015, 6650, 0, 0, },
        .ispGainR = { 235000000, 283000000, 399000000, 0, 0, },
        .ispGainG = { 100000000, 100000000, 100000000, 0, 0, },
        .ispGainB = { 264000000, 197000000, 137000000, 0, 0, },
        .coeff = {
            { { 146720000, 24630000, -71350000, }, { -52980000, 209770000, -56799999, }, { -22920000, -43190000, 166110000, }, },
            { { 157610000, 5930000, -63540000, }, { -58190000, 216950000, -58760000, }, { -35340000, 11270000, 124069999, }, },
            { { 251420000, -119530000, -31879998, }, { -21130000, 183990000, -62870000, }, { -4950000, -66069999, 171020000, }, },
            { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, },
            { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, },
        },
        .referenceRGB = {
            { 42, 71, 36},
            { 37, 71, 42},
            { 30, 67, 51},
            { 0, 0, 0},
            { 0, 0, 0},
        },
    },
    .contrast = {
        .enable = 0,
        .coeff.LUM_0 = 0,
        .coeff.LUM_32 = 0,
        .coeff.LUM_64 = 0,
        .coeff.LUM_96 = 0,
        .coeff.LUM_128 = 0,
        .coeff.LUM_160 = 0,
        .coeff.LUM_192 = 0,
        .coeff.LUM_224 = 0,
        .coeff.LUM_256 = 0,
    },
    .statAreaStatic = {
        .X0 = 1012,
        .Y0 = 760,
        .XSize = 2028,
        .YSize = 1520,
    },
    .gamma = {
        .enable = 1,
    },
    .sensorDelay = {
        .delay = 3,
    },
    .luxRef = {
        .HL_LuxRef = 1090,
        .HL_Expo1 = 8641,
        .HL_Lum1 = 37,
        .HL_Expo2 = 23041,
        .HL_Lum2 = 97,
        .LL_LuxRef = 240,
        .LL_Expo1 = 28948,
        .LL_Lum1 = 29,
        .LL_Expo2 = 63348,
        .LL_Lum2 = 64,
        .calibFactor = 0.998f,
    },
};

static const ISP_IQParamTypeDef* ISP_IQParamCacheInit[] = {
    &ISP_IQParamCacheInit_IMX477
};

#endif /* __ISP_PARAM_CONF__H */
