/**
 ******************************************************************************
 * @file    isp_param_conf.h
 * @author  AIS Application Team
 * @brief   Header file for IQT parameters of the ISP middleware.
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under SLA0044 terms that can be found here:
 * https://www.st.com/resource/en/license_agreement/SLA0044.txt
 *
 * THIS FILE WAS GENERATED BY THE STM32 ISP IQTune ON 2026-04-02 14:25:13
 *
 ******************************************************************************
 */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __ISP_PARAM_CONF__H
#define __ISP_PARAM_CONF__H

/* DCMIPP ISP configuration for VD66GY sensor */
static const ISP_IQParamTypeDef ISP_IQParamCacheInit_VD66GY = {
    .sensorGainStatic = {
        .gain = 0,
    },
    .sensorExposureStatic = {
        .exposure = 14361,
    },
    .AECAlgo = {
        .enable = 1,
        .exposureCompensation = EXPOSURE_TARGET_0_0_EV,
        .antiFlickerFreq = ANTIFLICKER_NONE,
    },
    .statRemoval = {
        .enable = 0,
        .nbHeadLines = 0,
        .nbValidLines = 0,
    },
    .badPixelStatic = {
        .enable = 0,
        .strength = 0,
    },
    .badPixelAlgo = {
        .enable = 0,
        .threshold = 0,
    },
    .blackLevelStatic = {
        .enable = 1,
        .BLCR = 16,
        .BLCG = 16,
        .BLCB = 16,
    },
    .demosaicing = {
        .enable = 1,
        .type = ISP_DEMOS_TYPE_GRBG,
        .peak = 2,
        .lineV = 4,
        .lineH = 4,
        .edge = 6,
    },
    .ispGainStatic = {
        .enable = 0,
        .ispGainR = 0,
        .ispGainG = 0,
        .ispGainB = 0,
    },
    .colorConvStatic = {
        .enable = 0,
        .coeff = { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, }
    },
    .AWBAlgo = {
        .enable = 1,
        .label = {
            "A",
            "TL84",
            "D65"
    },
        .referenceColorTemp = {
            2856,
            4000,
            6500
    },
        .ispGainR = {
            100000000,
            115999999,
            160000000
    },
        .ispGainG = {
            114999999,
            100000000,
            100000000
    },
        .ispGainB = {
            340000000,
            236000000,
            151000000
    },
        .coeff = {
            { { 112280000, 58030000, -70310000, }, { -54610000, 170290000, -15680000, }, { -18290000, -84050000, 202350000, }, },
            { { 124420000, 24910000, -49340000, }, { -45250000, 169890000, -24640000, }, { -11210000, -36350000, 147550000, }, },
            { { 130339999, 26629999, -56970000, }, { -36620000, 176410000, -39790000, }, { -9880000, -29320000, 139200000, }, }
    },
        .referenceRGB = {
            { 81, 63, 31},
            { 71, 71, 37},
            { 56, 69, 48}
    },
    },
    .contrast = {
        .enable = 0,
        .coeff.LUM_0 = 0,
        .coeff.LUM_32 = 0,
        .coeff.LUM_64 = 0,
        .coeff.LUM_96 = 0,
        .coeff.LUM_128 = 0,
        .coeff.LUM_160 = 0,
        .coeff.LUM_192 = 0,
        .coeff.LUM_224 = 0,
        .coeff.LUM_256 = 0,
    },
    .statAreaStatic = {
        .X0 = 225,
        .Y0 = 273,
        .XSize = 674,
        .YSize = 818,
    },
    .gamma = {
        .enable = 1,
    },
    .sensorDelay = {
        .delay = 4,
    },
    .luxRef = {
        .HL_LuxRef = 1000,
        .HL_Expo1 = 2000,
        .HL_Lum1 = 33,
        .HL_Expo2 = 7600,
        .HL_Lum2 = 123,
        .LL_LuxRef = 100,
        .LL_Expo1 = 17550,
        .LL_Lum1 = 29,
        .LL_Expo2 = 41229,
        .LL_Lum2 = 69,
        .calibFactor = 1.045f,
    },
};

static const ISP_IQParamTypeDef* ISP_IQParamCacheInit[] = {
    &ISP_IQParamCacheInit_VD66GY
};

#endif /* __ISP_PARAM_CONF__H */
