/**
 ******************************************************************************
 * @file    isp_param_conf.h
 * @author  AIS Application Team
 * @brief   Header file for IQT parameters of the ISP middleware.
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under SLA0044 terms that can be found here:
 * https://www.st.com/resource/en/license_agreement/SLA0044.txt
 *
 * THIS FILE WAS GENERATED BY THE STM32 ISP IQTune ON 2026-04-02 14:21:58
 *
 ******************************************************************************
 */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __ISP_PARAM_CONF__H
#define __ISP_PARAM_CONF__H

/* DCMIPP ISP configuration for VD66GY sensor */
static const ISP_IQParamTypeDef ISP_IQParamCacheInit_VD66GY = {
    .sensorGainStatic = {
        .gain = 0,
    },
    .sensorExposureStatic = {
        .exposure = 8928,
    },
    .AECAlgo = {
        .enable = 1,
        .exposureCompensation = EXPOSURE_TARGET_0_0_EV,
        .antiFlickerFreq = ANTIFLICKER_NONE,
    },
    .statRemoval = {
        .enable = 0,
        .nbHeadLines = 0,
        .nbValidLines = 0,
    },
    .badPixelStatic = {
        .enable = 0,
        .strength = 0,
    },
    .badPixelAlgo = {
        .enable = 0,
        .threshold = 0,
    },
    .blackLevelStatic = {
        .enable = 1,
        .BLCR = 16,
        .BLCG = 16,
        .BLCB = 16,
    },
    .demosaicing = {
        .enable = 1,
        .type = ISP_DEMOS_TYPE_GRBG,
        .peak = 2,
        .lineV = 4,
        .lineH = 4,
        .edge = 6,
    },
    .ispGainStatic = {
        .enable = 0,
        .ispGainR = 0,
        .ispGainG = 0,
        .ispGainB = 0,
    },
    .colorConvStatic = {
        .enable = 0,
        .coeff = { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, }
    },
    .AWBAlgo = {
        .enable = 1,
        .label = {
            "A",
            "TL84",
            "D65"
    },
        .referenceColorTemp = {
            2856,
            4000,
            6500
    },
        .ispGainR = {
            100000000,
            125000000,
            178000000
    },
        .ispGainG = {
            101000000,
            100000000,
            100000000
    },
        .ispGainB = {
            294000000,
            235000000,
            149000000
    },
        .coeff = {
            { { 141970000, 19990000, -61960000, }, { -54600000, 170770000, -16170000, }, { -13510000, -113620000, 227130000, }, },
            { { 124320000, 23360000, -47690000, }, { -45900000, 170200000, -24310000, }, { -11120000, -32170000, 143280000, }, },
            { { 141490000, 12120000, -53610000, }, { -42350000, 186570000, -44210000, }, { -13610000, -19760000, 133370000, }, }
    },
        .referenceRGB = {
            { 79, 71, 34},
            { 66, 70, 37},
            { 50, 69, 49}
    },
    },
    .contrast = {
        .enable = 0,
        .coeff.LUM_0 = 0,
        .coeff.LUM_32 = 0,
        .coeff.LUM_64 = 0,
        .coeff.LUM_96 = 0,
        .coeff.LUM_128 = 0,
        .coeff.LUM_160 = 0,
        .coeff.LUM_192 = 0,
        .coeff.LUM_224 = 0,
        .coeff.LUM_256 = 0,
    },
    .statAreaStatic = {
        .X0 = 225,
        .Y0 = 273,
        .XSize = 674,
        .YSize = 818,
    },
    .gamma = {
        .enable = 1,
    },
    .sensorDelay = {
        .delay = 4,
    },
    .luxRef = {
        .HL_LuxRef = 1000,
        .HL_Expo1 = 1380,
        .HL_Lum1 = 24,
        .HL_Expo2 = 6980,
        .HL_Lum2 = 121,
        .LL_LuxRef = 100,
        .LL_Expo1 = 15584,
        .LL_Lum1 = 29,
        .LL_Expo2 = 42293,
        .LL_Lum2 = 75,
        .calibFactor = 0.964f,
    },
};

static const ISP_IQParamTypeDef* ISP_IQParamCacheInit[] = {
    &ISP_IQParamCacheInit_VD66GY
};

#endif /* __ISP_PARAM_CONF__H */
