/**
 ******************************************************************************
 * @file    isp_param_conf.h
 * @author  AIS Application Team
 * @brief   Header file for IQT parameters of the ISP middleware.
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under SLA0044 terms that can be found here:
 * https://www.st.com/resource/en/license_agreement/SLA0044.txt
 *
 * THIS FILE WAS GENERATED BY THE STM32 ISP IQTune ON 2026-04-02 14:19:51
 *
 ******************************************************************************
 */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __ISP_PARAM_CONF__H
#define __ISP_PARAM_CONF__H

/* DCMIPP ISP configuration for VD66GY sensor */
static const ISP_IQParamTypeDef ISP_IQParamCacheInit_VD66GY = {
    .sensorGainStatic = {
        .gain = 0,
    },
    .sensorExposureStatic = {
        .exposure = 9000,
    },
    .AECAlgo = {
        .enable = 1,
        .exposureCompensation = EXPOSURE_TARGET_0_0_EV,
        .antiFlickerFreq = ANTIFLICKER_NONE,
    },
    .statRemoval = {
        .enable = 0,
        .nbHeadLines = 0,
        .nbValidLines = 0,
    },
    .badPixelStatic = {
        .enable = 0,
        .strength = 0,
    },
    .badPixelAlgo = {
        .enable = 0,
        .threshold = 0,
    },
    .blackLevelStatic = {
        .enable = 1,
        .BLCR = 16,
        .BLCG = 16,
        .BLCB = 16,
    },
    .demosaicing = {
        .enable = 1,
        .type = ISP_DEMOS_TYPE_GRBG,
        .peak = 2,
        .lineV = 4,
        .lineH = 4,
        .edge = 6,
    },
    .ispGainStatic = {
        .enable = 0,
        .ispGainR = 0,
        .ispGainG = 0,
        .ispGainB = 0,
    },
    .colorConvStatic = {
        .enable = 0,
        .coeff = { { 0, 0, 0, }, { 0, 0, 0, }, { 0, 0, 0, }, }
    },
    .AWBAlgo = {
        .enable = 1,
        .label = {
            "A",
            "TL84",
            "D65"
    },
        .referenceColorTemp = {
            2856,
            4000,
            6500
    },
        .ispGainR = {
            100000000,
            120000000,
            170000000
    },
        .ispGainG = {
            106000000,
            100000000,
            100000000
    },
        .ispGainB = {
            318000000,
            243000000,
            153000000
    },
        .coeff = {
            { { 134890000, 37110000, -72000000, }, { -48340000, 167930000, -19580000, }, { -12659999, -107830000, 220490000, }, },
            { { 137640000, 2360000, -40000000, }, { -42550000, 158430000, -15880000, }, { -6130000, -52240000, 158360000, }, },
            { { 125630000, 29570000, -55200000, }, { -37280000, 173990000, -36710000, }, { -10060000, -26240000, 136300000, }, }
    },
        .referenceRGB = {
            { 82, 68, 32},
            { 69, 70, 37},
            { 55, 70, 48}
    },
    },
    .contrast = {
        .enable = 0,
        .coeff.LUM_0 = 0,
        .coeff.LUM_32 = 0,
        .coeff.LUM_64 = 0,
        .coeff.LUM_96 = 0,
        .coeff.LUM_128 = 0,
        .coeff.LUM_160 = 0,
        .coeff.LUM_192 = 0,
        .coeff.LUM_224 = 0,
        .coeff.LUM_256 = 0,
    },
    .statAreaStatic = {
        .X0 = 225,
        .Y0 = 273,
        .XSize = 674,
        .YSize = 818,
    },
    .gamma = {
        .enable = 1,
    },
    .sensorDelay = {
        .delay = 4,
    },
    .luxRef = {
        .HL_LuxRef = 1000,
        .HL_Expo1 = 1200,
        .HL_Lum1 = 25,
        .HL_Expo2 = 6000,
        .HL_Lum2 = 124,
        .LL_LuxRef = 100,
        .LL_Expo1 = 13633,
        .LL_Lum1 = 29,
        .LL_Expo2 = 29633,
        .LL_Lum2 = 64,
        .calibFactor = 0.980f,
    },
};

static const ISP_IQParamTypeDef* ISP_IQParamCacheInit[] = {
    &ISP_IQParamCacheInit_VD66GY
};

#endif /* __ISP_PARAM_CONF__H */
